// <auto-generated />
namespace Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VMElan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VMElan));
        
        string IMigrationMetadata.Id
        {
            get { return "201908060557236_VMElan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
